### PR TITLE
rewrite angular code with class syntax and move tsd to typings

### PR DESCRIPTION
**Pull request by sylvaindumont**
Just rewrite angular code with a class and install typings via typings instead of tsd.

### CODE REVIEW

**Comment by ConcurrentHashMap** [comment]
Hey Sylvain,

thanks for this contribution. You've made it have even better coding style and more class-like. I've just added a comment onto one "problem" I found with this PR, but I will definitely merge this, as it is really good! Thanks for that!

Did you already get your hands on Angular 2? Maybe we could rewrite (or better make a second repository/branch) as a starter pack for using Angular 2 with TypeScript and modules. Would you be interested?

**Comment by sylvaindumont** [comment]
Hey,

Sorry for the forgotten import in the readme, one failed copy past it's fixed now.
It would be cool to have an angular2 branch or repo. I have already written some things in angular2 and I can write an angular 2 expample.

**Comment by ConcurrentHashMap** [comment]
Maybe we should start using a separate branch and link the branch in the README. I added you as a collaborator for this repo. Have fun :)

**Comment by ConcurrentHashMap** [comment]
Thanks for this awesome contribution!

**Pull request merged**
